# Name of your application. Used to uniquely configure containers.
service: react-importmap

# Name of the container image.
image: tiyalcin/react-importmap
volumes:
  - "data:/data"
servers:
  web:
    hosts:
      - 104.248.37.37 # digitalocean
    options:
      "add-host": host.docker.internal:host-gateway
    labels:
      # gzip
      traefik.http.middlewares.websecure-compress.compress: true
      traefik.http.routers.websecure.middlewares: websecure-compress@docker
      traefik.http.routers.websecure.rule: Host(`saas.ruby-rails.net`)
      traefik.http.routers.websecure.entrypoints: websecure
      traefik.http.routers.websecure.tls.certresolver: letsencrypt      

registry:
  username: tiyalcin
  password:
    - KAMAL_REGISTRY_PASSWORD
env:
  clear:
  secret:
    - RAILS_MASTER_KEY
traefik:
  options:
    publish:
      - "443:443"
    volume:
      - "/letsencrypt/acme.json:/letsencrypt/acme.json"
  args:
    entryPoints.web.address: ":80"
    entryPoints.websecure.address: ":443"
    entryPoints.web.http.redirections.entryPoint.to: websecure
    entryPoints.web.http.redirections.entryPoint.scheme: https
    entryPoints.web.http.redirections.entrypoint.permanent: true
    entrypoints.websecure.http.tls: true
    certificatesResolvers.letsencrypt.acme.email: "tiyalcin@gmail.com"
    certificatesResolvers.letsencrypt.acme.storage: "/letsencrypt/acme.json"
    certificatesResolvers.letsencrypt.acme.httpchallenge: true
    certificatesResolvers.letsencrypt.acme.httpchallenge.entrypoint: web