test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

# contabo config
# cloud:
#   service: S3
#   endpoint: https://eu2.contabostorage.com
#   access_key_id: <%= ENV['S3_ACCESS_KEY_ID'] %>
#   secret_access_key: <%= ENV['S3_SECRET_ACCESS_KEY'] %>
#   region: eu2
#   bucket: rails-upload-test
#   force_path_style: true

wasabi:
  service: S3
  endpoint: https://s3.eu-central-2.wasabisys.com
  access_key_id: <%= ENV['WASABI_ACCESS_KEY'] %>
  secret_access_key: <%= ENV['WASABI_SECRET_KEY'] %>
  region: eu-central-2
  bucket: rails-wasabi

cloudflare:
  service: S3
  endpoint: https://f847343fcebb834f024e741e044d3552.r2.cloudflarestorage.com
  access_key_id: de08d3df1babc94069c83f9434ef6284
  secret_access_key: 386943223307193bba9c2de7285f685a70178f49dd462f308072f43021323f53
  region: auto
  bucket: rails-r2  

production:
  service: S3
  endpoint: https://s3.eu-central-2.wasabisys.com
  access_key_id: <%= Rails.application.credentials.dig(:wasabi, :S3_ACCESS_KEY_ID) %>
  secret_access_key: <%= Rails.application.credentials.dig(:wasabi, :S3_SECRET_ACCESS_KEY) %>
  region: eu-central-2
  bucket: rails-wasabi
